[metadata]
author: "JPxG"
title: "Default JoyStuck bindings"
date: "2022-01-03"
enabled: "yes"
sounds: "on"

[buttons]
# Basic format looks like this:
# "1":"page up"
# "1+2":"ctrl+page up"
#
# One of these must be set to "toggle", which toggles to next binding set.
# If none is specified, it will use 12.
#
# Special key names are as follows:
#       left, right, up, down, esc, f1, f2 [...] f12,
#       caps lock, scroll lock, num lock, pause,
#       insert, delete, home, end, page up, page down,
#       ctrl, alt, shift, tab, space, and menu.
# Numpad symbols are parsed differently from same keys on keyboard.
#       / = "รท", * = "ร", - = "-", and + = "+" (enter is still "enter").
# Numpad keys are not affected by num lock being on: numpad "del"
#       parses as "." even if it produces "delete" on the computer.
# Shift is not parsed into keypresses (i.e. * is "8").
#
# Note: Combos must be specified in increasing order.
#       "1+2" is valid, "2+1" is not.
"1":  "page up"
"1+2": "ctrl+page up"
"3":  ""
"4":  ""
"5":  ""
"6":  ""
"7":  ""
"8":  ""
"9":  ""
"10": ""
"11": ""
"12": "toggle"

[hat]
# Hat switch directions: "u", "d", "l", and "r".
# Also takes combos: "ul", "ur", "dr" and "dl".
"u": ""
"d": ""
"l": ""
"r": ""
"ul": ""
"ur": ""
"dl": ""
"dr": ""

[axes]
# X is left-to right   (minus is left and plus is right).
# Y is towards-to-away (minus is away and plus is toward).
# Z is twist           (minus is counterclockwise and plus is clockwise).
# Damping means "send another keystroke for each __ positions past neutral".
# Acceptable values for X are 0 to 511.
# Acceptable values for Y are 0 to 511.
# Acceptable values for Z are 0 to 127.
# Damping can also be "off", in which case a single keystroke
# will be sent when the value crosses a threshold.
# The threshold value defaults to halfway pulled in whatever direction
# (255 for x/y, 64 for z). If damping is on, "threshold" is unused.

""
"xminus": "left"
"xplus": "right"
"yminus": "up"
"yplus": "down"
"zminus": "shift+tab"
"zplus": "tab"
"xdamping": 32
"ydamping": 32
"zdamping": 8
"xthreshold": 255
"ythreshold": 255
"zthreshold": 64



# "sounds1" through "sounds100" can be specified.
# They work the same way as the others.
# "path" must either be "absolute" or "relative".
# For "relative", they will be taken from /snd.

[sounds1]
"path": "absolute"
"1": "/home/x/2k2k/sound/saw-220-1s-08-taperafter01.wav"
"2": "/home/x/2k2k/sound/saw-440-1s-08-taperafter01.wav"
"3": "/home/x/2k2k/sound/saw-494-1s-08-taperafter01.wav"
"4": "/home/x/2k2k/sound/saw-523-1s-08-taperafter01.wav"
"5": "/home/x/2k2k/sound/saw-587-1s-08-taperafter01.wav"
"6": "/home/x/2k2k/sound/saw-659-1s-08-taperafter01.wav"
"7": "/home/x/2k2k/sound/saw-698-1s-08-taperafter01.wav"
"8": "/home/x/2k2k/sound/saw-783-1s-08-taperafter01.wav"
"9": "/home/x/2k2k/sound/saw-880-1s-08-taperafter01.wav"
"10": ""
"11": ""
"12": ""

"hatu": ""
"hatd": ""
"hatl": ""
"hatr": ""

"hatul": ""
"hatur": ""
"hatdl": ""
"hatdr": ""

"xminus": ""
"xplus":  ""

"yminus": ""
"yplus":  ""

"zminus": ""
"zplus":  ""

[sounds2]
"path": "absolute"
"1": ""
"2": ""
"3": ""
"4": ""
"5": ""
"6": ""
"7": ""
"8": ""
"9": ""
"10": ""
"11": ""
"12": ""

"hatu": ""
"hatd": ""
"hatl": ""
"hatr": ""

"hatul": ""
"hatur": ""
"hatdl": ""
"hatdr": ""

"xminus": ""
"xplus":  ""

"yminus": ""
"yplus":  ""

"zminus": ""
"zplus":  ""
