[metadata]
author   = "JPxG"
title    = "Default JoyStuck bindings"
date     = "2022-01-03"
enabled  = "yes"
sounds   = "on"

##################################################
# Basic format looks like this:
#       "1":"page up"
#       "1+2":"ctrl+page up"
#
# One of these must be set to "toggle", which toggles to next binding set.
#       If none is specified, it will use 12.
#
# Additionally, one of these SHOULD be set to "togglesound".
#       This will make that button toggle through each soundpack
#       (when the bindings are initially loaded, it will be silent
#       and you will have to togglesound to get to the first one).
#
#       Otherwise, there is no silent mode, and the first soundpack
#       will be the only usable one for this binding scheme.
#
# Special key names are as follows:
#       left, right, up, down, esc, f1, f2 [...] f12,
#       caps lock, scroll lock, num lock, pause,
#       insert, delete, home, end, page up, page down,
#       ctrl, alt, shift, tab, space, and menu.
#
# Numpad symbols are parsed differently from same keys on keyboard.
#       / = "รท", * = "ร", - = "-", and + = "+" (enter is still "enter").
# Numpad keys are not affected by num lock being on: numpad "del"
#       parses as "." even if it produces "delete" on the computer.
# Shift is not parsed into keypresses (i.e. * is "8").
#
# Note: Combos must be specified in increasing order.
#       "1+2" is valid, "2+1" is not.
##################################################
[buttons]
"1"      = "enter"
"2"      = "ctrl+w"
"3"      = ""
"4"      = ""
"5"      = ""
"6"      = "ctrl+page up"
"7"      = "ctrl+page down"
"8"      = ""
"9"      = ""
"10"     = ""
"11"     = "togglesound"
"12"     = "toggle"

##################################################
# Hat switch directions: "u", "d", "l", and "r".
# Also takes combos: "ul", "ur", "dr" and "dl".
##################################################
[hat]
"u"      = ""
"d"      = ""
"l"      = ""
"r"      = ""
"ul"     = ""
"ur"     = ""
"dl"     = ""
"dr"     = ""

##################################################
# X is left-to right   (minus is left and plus is right).
# Y is towards-to-away (minus is away and plus is toward).
# Z is twist           (minus is counterclockwise and plus is clockwise).
# Damping means "send another keystroke for each __ positions past neutral".
# Acceptable values for X are 0 to 511.
# Acceptable values for Y are 0 to 511.
# Acceptable values for Z are 0 to 127.
# Damping can also be "off", in which case a single keystroke
# will be sent when the value crosses a threshold.
# The threshold value defaults to halfway pulled in whatever direction
# (255 for x/y, 64 for z). If damping is on, "thres" is unused.
##################################################
[axes]
"xminus" = "left"
"xplus"  = "right"

"yminus" = "up"
"yplus"  = "down"

"zminus" = "shift+tab"
"zplus"  = "tab"

"xdamp"  = 32
"ydamp"  = 32
"zdamp"  = 16

"xthres" = 255
"ythres" = 255
"zthres" = 64

##################################################
# Note: Combos must be given in increasing order.
#       "1+2" is valid, "2+1" is not.
##################################################
[combos]
"1+2"    = "ctrl+page up"


##################################################
# Sounds can be included, [sounds.1] through whatever number.
# Don't skip numbers.
# Input buttons are the same as for the hotkeys.
#
# Multiple sounds can be given for one button/combo:
# "1": ["badabing.wav", "badaboom.wav"]
# Or just one:
# "2": "powrightinthekisser.wav"
#
# "path" must either be "absolute" or "relative".
# For "relative", they will be taken from /snd.
##################################################
[sounds.1]
"path"   = "absolute"
"1"      = "/home/x/2k2k/sound/saw-220-1s-08-taperafter01.wav"
"2"      = "/home/x/2k2k/sound/saw-440-1s-08-taperafter01.wav"
"3"      = "/home/x/2k2k/sound/saw-494-1s-08-taperafter01.wav"
"4"      = "/home/x/2k2k/sound/saw-523-1s-08-taperafter01.wav"
"5"      = "/home/x/2k2k/sound/saw-587-1s-08-taperafter01.wav"
"6"      = "/home/x/2k2k/sound/saw-659-1s-08-taperafter01.wav"
"7"      = "/home/x/2k2k/sound/saw-698-1s-08-taperafter01.wav"
"8"      = "/home/x/2k2k/sound/saw-783-1s-08-taperafter01.wav"
"9"      = "/home/x/2k2k/sound/saw-880-1s-08-taperafter01.wav"
"10"     = ""
"11"     = ""
"12"     = "sine-880-to-440-badomp-1s-08-taper.wav"

"hatu"   = ""
"hatd"   = ""
"hatl"   = ""
"hatr"   = ""

"hatul"  = ""
"hatur"  = ""
"hatdl"  = ""
"hatdr"  = ""

"xminus" = ""
"xplus"  = ""

"yminus" = ""
"yplus"  = ""

"zminus" = ""
"zplus"  = ""

##################################################
[sounds.2]
"path"   = "absolute"
"1"      = "/home/x/2k2k/sound/twispark-15ai-b1.wav"
"2"      = "/home/x/2k2k/sound/twispark-15ai-2.wav"
"3"      = "/home/x/2k2k/sound/twispark-15ai-3.wav"
"4"      = "/home/x/2k2k/sound/twispark-15ai-4.wav"
"5"      = "/home/x/2k2k/sound/twispark-15ai-5.wav"
"6"      = "/home/x/2k2k/sound/twispark-15ai-6.wav"
"7"      = "/home/x/2k2k/sound/twispark-15ai-7.wav"
"8"      = "/home/x/2k2k/sound/twispark-15ai-8.wav"
"9"      = "/home/x/2k2k/sound/twispark-15ai-9.wav"
"10"     = "/home/x/2k2k/sound/twispark-15ai-10.wav"
"11"     = "/home/x/2k2k/sound/twispark-15ai-11.wav"
"12"     = "/home/x/2k2k/sound/twispark-15ai-toggling.wav"

"hatu"   = ""
"hatd"   = ""
"hatl"   = ""
"hatr"   = ""

"hatul"  = ""
"hatur"  = ""
"hatdl"  = ""
"hatdr"  = ""

"xminus" = ""
"xplus"  = ""

"yminus" = ""
"yplus"  = ""

"zminus" = ""
"zplus"  = ""
##################################################
